stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: Dockerfile
      buildContext: .
      tag: fiware-idm-7.7
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
timeout: 60
notification:
  recipients:
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-4927h
  condition:
  - Success
  - Changed
  - Failed
