stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./keyrock-deployment.yaml
  - applyYamlConfig:
      path: ./keyrock-service.yaml
timeout: 300
notification:
  recipients:
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-4927h
  condition:
  - Success
  - Changed
  - Failed
