apiVersion: v1
kind: Service
metadata:
  name: keyrockserv
spec:
  externalIPs:
  - 192.168.100.171
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - name: keyrockport
    port: 3000
    protocol: TCP
    nodePort: 30052
    targetPort: 3000
  selector:
    workloadID_keyrockserv: "true"
  sessionAffinity: None
