apiVersion: v1
kind: Service
metadata:
  labels:
    name: keyrockserv
  name: keyrockserv
  namespace: default
spec:
  externalIPs:
  - 192.168.100.171
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
  - name: keyrockport
    port: 3000
    nodePort: 30052
  selector:
    name: keyrock
